HOST_CC ?= cc
HOST_BUILD := build-host
HOST_CFLAGS := -std=c11 -Wall -Wextra -Wpedantic -Werror -O1 -g \
               -fsanitize=address,undefined -fno-omit-frame-pointer -Iinclude
HOST_SOURCES := source/localsend_protocol.c source/device_registry.c source/http_server.c \
                source/discovery.c
HOST_TEST_SOURCES := tests/test_main.c tests/logger_stub.c
HOST_TEST := $(HOST_BUILD)/localsend3ds_tests

.PHONY: test clean

test: $(HOST_TEST)
	@$(HOST_TEST)

$(HOST_TEST): $(HOST_SOURCES) $(HOST_TEST_SOURCES) | $(HOST_BUILD)
	$(HOST_CC) $(HOST_CFLAGS) $^ -o $@

$(HOST_BUILD):
	@mkdir -p $@

clean:
	@rm -rf $(HOST_BUILD)
